#
# DEBUG Multipart
#

SecRule REQUEST_BODY "@contains Content-Disposition" \
"id:9999901,\
phase:2,\
pass,\
log,\
auditlog,\
msg:'REQUEST_BODY contains Content-Disposition'"

SecRule REQUEST_BODY "@rx (?s)name=\"a\".*?RmlsZXNNQW4=" \
"id:9999910,\
phase:2,\
pass,\
log,\
msg:'Found parameter a'"

SecRule REQUEST_BODY "@rx (?s)name=\"alfa1\".*?dXBsb2FkRmlsZQ==" \
"id:9999911,\
phase:2,\
pass,\
log,\
auditlog,\
msg:'Found alfa1'"

SecRule ARGS:a "@rx .*" \
"id:9999920,\
phase:2,\
pass,\
log,\
msg:'ARGS:a=%{MATCHED_VAR}'"

SecRule ARGS:alfa1 "@rx .*" \
"id:9999921,\
phase:2,\
pass,\
log,\
msg:'ARGS:alfa1=%{MATCHED_VAR}'"

SecRule FILES_NAMES "@rx .*" \
"id:9999922,\
phase:2,\
pass,\
log,\
msg:'FILES_NAMES=%{MATCHED_VAR}'"