#
# DEBUG Multipart
#

SecRule REQUEST_BODY "@contains Content-Disposition" \
"id:9999901,\
phase:2,\
pass,\
log,\
auditlog,\
msg:'REQUEST_BODY contains Content-Disposition'"

SecRule REQUEST_BODY "@rx (?s)name=\"a\".*?RmlsZXNNQW4=" \
"id:9999910,\
phase:2,\
pass,\
log,\
msg:'Found parameter a'"